#!/bin/bash

# assumes:
# git clone --recurse-submodules git://github.com/openmicroscopy/omero-test-infra .omero

set -e
set -u

DIR=${DIR:-.}
PROJECT=${PROJECT:-omero}
CID=${CID:-"$PROJECT"_web_1}
TARGET=/$(basename $PWD)
.omero/compose up -d --force-recreate
docker cp -L .      $CID:/$TARGET
docker cp -L .omero $CID:/infra
docker exec -u root -e TARGET=$TARGET $CID sh -c "chown -R omero-web:omero-web $TARGET /infra"


# Workarounds
# https://github.com/openmicroscopy/omero-web-docker/pull/17
docker exec $CID sed -i "s/^\(omero\.host\s*=\s*\).*\$/\1omero/" /opt/omero/web/OMERO.web/etc/ice.config
# Need Java for importing
docker exec -e USER_AGENT=Travis -u root $CID /opt/omero/omego/bin/omego download java --sym /opt/omero/java
docker exec $CID ln -s /opt/omero/java/libs /opt/omero/web/OMERO.web/lib/client

# Run custom dependencies setup
if [ -e .omeroci/app-deps ]; then
  docker exec -u root $CID bash /$TARGET/.omeroci/app-deps
fi

docker exec -e OMERO_HOST=omero $CID /infra/wait-on-login
# install setuptools and requirement
docker exec -u root -e TARGET=$TARGET $CID /infra/py-common
if [ -e .omeroci/app-check ]; then
  docker exec -u root $CID bash /$TARGET/.omeroci/app-check
else 
  docker exec -u root -e TARGET=$TARGET $CID /infra/py-check
fi

docker exec -u root -e TARGET=$TARGET $CID /infra/py-setup

# Run custom server setup
if [ -e .omeroci/app-config ]; then
  docker exec $CID bash /$TARGET/.omeroci/app-config
else
  NAME=$(echo $(basename $PWD) | tr - _)
  docker exec -e NAME=$NAME $CID /infra/app-config
fi

docker exec  -u root -e TARGET=$TARGET -e DIR=$DIR $CID /infra/app-build
