#!/bin/bash

source /infra/utils

set -e
set -u
set -x

cd $TARGET
DIR=$(setup_dir)

export PYTHONPATH=$PYTHONPATH:${OMERO_DIST}/lib/python/omeroweb
# TBD: unify on test or tests
# TBD: needs setup.py infra
# python setup.py test -t test* -i ${OMERO_DIST}/etc/ice.config -v

set +u
source /opt/omero/web/venv/bin/activate
ICE_CONFIG=${OMERO_DIST}/etc/ice.config python $DIR/setup.py test
