#!/bin/bash
set -e
set +u

source /infra/utils

cd $TARGET

# format the name of the app
name=$(get_app_name)

source /opt/omero/web/venv/bin/activate
/opt/omero/web/OMERO.web/bin/omero config append omero.web.apps '"$name"'
