#!/bin/bash
source /infra/utils

set -e
set +u

cd $TARGET

# format the name of the app
value="[\""$(get_app_name)"\"]"

su - omero-web -c "/opt/omero/web/venv3/bin/omero config set omero.web.apps $value"
