#!/bin/bash

# assumes:
# git clone --recurse-submodules git://github.com/openmicroscopy/test-omero .omero

set -e
set -u

PROJECT=${PROJECT:-omero}
CID=${CID:-"$PROJECT"_web_1}
TARGET=/$(basename $PWD)
.omero/compose up -d --force-recreate
docker cp -L .      $CID:/$TARGET
docker cp -L .omero $CID:/test-omero
docker exec -u root -e TARGET=$TARGET $CID sh -c "chown -R omero-web:omero-web $TARGET /test-omero"

# Workarounds
# https://github.com/openmicroscopy/omero-web-docker/pull/17
docker exec $CID sed -i "s/^\(omero\.host\s*=\s*\).*\$/\1omero/" /opt/omero/web/OMERO.web/etc/ice.config
# Need Java for importing
docker exec -e USER_AGENT=Travis -u root $CID /opt/omero/omego/bin/omego download java --sym /opt/omero/java
docker exec $CID ln -s /opt/omero/java/libs /opt/omero/web/OMERO.web/lib/client

docker exec -e OMERO_HOST=omero $CID /test-omero/wait-on-login
docker exec -u root -e TARGET=$TARGET $CID /test-omero/py-setup

# Run custom server setup
if [ -e .omeroci/app-config ];
then
  docker exec $CID bash /$TARGET/.omeroci/app-config
fi

docker exec         -e TARGET=$TARGET $CID /test-omero/app-build
