#!/bin/bash

set -e
set -u
set -x

printf "travis_fold:start:app-build\n"

TARGET=${TARGET:-..}
cd $TARGET

GUESS=${PWD#*omero-*}
PLUGIN=${PLUGIN:-$GUESS}

export OMERO_DIST=${OMERO_DIST:-/opt/omero/web/OMERO.web}
export PYTHONPATH=${OMERO_DIST}/lib/python:${OMERO_DIST}/lib/python/omeroweb
# TBD: unify on test or tests
# TBD: needs setup.py infra
# python setup.py test -t test* -i ${OMERO_DIST}/etc/ice.config -v

set +u
source /opt/omero/web/venv/bin/activate
ICE_CONFIG=${OMERO_DIST}/etc/ice.config python setup.py test

printf "travis_fold:end:app-build\n"
