#!/bin/bash
source /infra/utils

set -e
set +u

cd $TARGET

# format the name of the app
value="[\""$(get_app_name)"\"]"

source /opt/omero/web/venv/bin/activate
$OMERO_DIST/bin/omero config set omero.web.apps $value
