#!/bin/sh

set -e
set -u
set -x

printf "travis_fold:start:cli-setup\n"

TARGET=${TARGET:-..}

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $TARGET
pip install --upgrade pip setuptools
pip install -r $dir/cli-requirements.txt
rst-lint README.rst

python setup.py sdist
pip install dist/*.tar.gz
python setup.py clean
rm -rf dist src/*egg-info

printf "travis_fold:end:cli-setup\n"
