#!/bin/bash

set -e
set -u
set -x

TARGET=${TARGET:-..}
cd $TARGET

GUESS=${PWD#*omero-cli-*}
PLUGIN=${PLUGIN:-$GUESS}

export OMERO_DIST=${OMERO_DIST:-/opt/omero/server/OMERO.server}
$OMERO_DIST/bin/omero $PLUGIN -h

export PYTHONPATH=${OMERO_DIST}/lib/python
python setup.py test -t test/integration/clitest -i ${OMERO_DIST}/etc/ice.config -v
