#!/bin/bash

# assumes:
# git clone --recurse-submodules git://github.com/openmicroscopy/test-omero .omero

set -e
set -u

CID=${CID:-omero_omero_1}
TARGET=/$(basename $PWD)
.omero/compose up -d --force-recreate
docker cp -L .      $CID:/$TARGET
docker cp -L .omero $CID:/test-omero
docker exec -u root -e TARGET=$TARGET $CID sh -c "chown -R omero-server:omero-server $TARGET /test-omero"
docker exec -u root -e TARGET=$TARGET $CID /test-omero/cli-setup
docker exec         -e TARGET=$TARGET $CID /test-omero/cli-build
