#!/bin/bash
set -e
set -u

##
## Bash configuration
##

. .omero/utils
export ACTION=${ACTION:-""}
export TRAVIS=${TRAVIS:-"false"}
export VERBOSE=${VERBOSE:-"set +x"}
export PROJECT=${PROJECT:-$(get_project_name)}
export NETWORK=${NETWORK:-"$PROJECT"_default}
export TARGET=/$(basename $PWD)

if [ $# -eq 0 ]; then
    echo "docker [stage [stage [stage]]]"
    echo
    echo "Stages:"
    echo "  app     - installs plugin into OMERO.web"
    echo "  cli     - installs plugin into OMERO.server"
    echo "  lib     - builds and runs client-side library"
    echo "  scripts - installs OMERO.scripts into OMERO.server"
    echo
    echo "Environment variables:"
    echo "  PROJECT - name of the docker-compose project ($PROJECT)"
    echo "  NETWORK - name of the docker network to use ($NETWORK)"
    echo "  TARGET  - name of the component being installed ($TARGET)"
    echo "  ACTION  - use 'echo' to perform a dry-run ($ACTION)"
    echo "  TRAVIS  - whether to print travis_folds ($TRAVIS)"
    echo "  VERBOSE - set to 'set -x' to see all actions ($VERBOSE)"
    exit 2
else
    STAGES="$@"
fi

$VERBOSE

start_up() {
    $ACTION .omero/compose up -d --force-recreate "$@"
}

##
## Stages
##

fold() {
    if [ "$TRAVIS" == "true" ]; then
        printf "travis_fold:$1:$2\n"
    fi
}

run() {
    # Primary task which uses the first two arguments to either:
    #  1) run .omeroci/$1-$2 if it exists, or
    #  2) run the default script in this directory of the same name.

    LOCAL=false
    CALLAS="-u root"
    if [ $1 == "--local" ]; then
        LOCAL=true
        shift
    elif [ $1 == "--user" ]; then
        CALLAS="-u $USER"
        shift
    fi

    type=$1
    name=$2
    file="$1-$2"
    var="${CID}_$(echo $1| tr /a-z/ /A-Z/)_$(echo $2 | tr /a-z/ /A-Z/)"
    eval "$var=\${$var:-0}"

    if [ "${!var}" == "1" ]; then
        echo "$file already run for $CID"
    else
        eval "$var=1"
        fold start $file
        if [ -e .omeroci/$file ]; then
            PREFIX=/$TARGET
            LOCALPREFIX=""
            ARGUMENT=.omeroci/$file
        elif [ -e $(dirname "$0")/$file ]; then
            PREFIX=/infra
            LOCALPREFIX=".omero"
            ARGUMENT=$file
        elif [ -e $(dirname "$0")/$STAGE-$name ]; then
            PREFIX=/infra
            LOCALPREFIX=".omero"
            ARGUMENT=$STAGE-$name
        else
            echo "No script found:"
            echo "  .omeroci/$file"
            echo "  $(dirname "$0")/$file"
            echo "  $(dirname "$0")/$STAGE-$name"
            return 2
        fi
        if [ "$LOCAL" == true ]; then
            $ACTION $LOCALPREFIX/$ARGUMENT
        else
            $ACTION docker exec $CALLAS -e TARGET=$TARGET -e OMERO_DIST=$OMERO_DIST $CID $PREFIX/$ARGUMENT
        fi
        fold end $file
    fi
}

install() {
    if [ $# -eq 0 ] || [ $1 != "--nosrc" ]; then
        $ACTION docker cp -L .      $CID:/$TARGET
        $ACTION docker exec -u root -e TARGET=$TARGET $CID sh -c "chown -R $USER:$USER $TARGET"
    fi
    $ACTION docker cp -L .omero $CID:/infra
    $ACTION docker exec -u root $CID sh -c "chown -R $USER:$USER /infra"
}

java() {
    $ACTION docker exec -e USER_AGENT=Travis -u root $CID /opt/omero/omego/bin/omego download java --sym /opt/omero/java
    $ACTION docker exec $CID ln -s /opt/omero/java/libs /opt/omero/web/OMERO.web/lib/client
}

wait_on_login() {
    OMERO_HOST="-e OMERO_HOST=omero"
    if [ $# -gt 0 ] && $1 == "--localhost" ]; then
        OMERO_HOST=""
        shift
    fi
    $ACTION docker exec $OMERO_HOST $CID /infra/wait-on-login
}

##
## RUN STAGES
##

for STAGE in $STAGES; do
    export $STAGE
    case "$STAGE" in
        app)
            export COMPONENT=web
            export USER=omero-web
            export CID="$PROJECT"_web_1
            export OMERO_DIST="/opt/omero/web/OMERO.web"
            start_up
            install
            java
            run app deps || echo ignore
            # As the only web-container action
            # give the app a chance to modify
            # the docker container. This may
            # need to be formalized later.
            (
                USER=omero-server
                CID="${PROJECT}_omero_1"
                OMERO_DIST="/opt/omero/server/OMERO.server"
                install
                run app srv || echo ignore
            )
            wait_on_login
            run py common
            run py check
            run py setup
            run --user app config
            run --user app build
            ;;
        cli)
            export COMPONENT=server
            export USER=omero-server
            export CID="$PROJECT"_omero_1
            export OMERO_DIST="/opt/omero/server/OMERO.server"
            start_up
            install
            wait_on_login
            run py update
            run py setup
            run --user cli build
            ;;
        lib)
            export COMPONENT=server
            export USER=omero-server
            export CID="$PROJECT"_omero_1
            export OMERO_DIST="/opt/omero/server/OMERO.server"
            start_up
            install
            run --local lib build
            wait_on_login
            run --user test data || echo ignore
            run --local lib test
            ;;
        scripts)
            export COMPONENT=server
            export USER=omero-server
            export CID="$PROJECT"_omero_1
            export OMERO_DIST="/opt/omero/server/OMERO.server"
            start_up
            install
            run scripts deps || echo ignore
            run py common
            run py check
            run py setup
            run scripts copy
            wait_on_login
            run --user test data || echo ignore
            run py update
            run --user scripts build
            ;;
        srv)
            export COMPONENT=server
            export USER=omero-server
            export CID="$PROJECT"_omero_1
            export COMPOSE_FILE=${COMPOSE_FILE:-"srv-compose.yml"}
            export OMERO_DIST="/opt/omero/server/OMERO.server"
            start_up
            install --nosrc
            run py common
            wait_on_login --localhost
            run --user srv test
            ;;
        *)
            echo "Unknown stage: $STAGE"
            exit 2
            ;;
    esac
done
