#!/bin/bash
source /infra/utils

set -e
set -u
set -x

TARGET=${TARGET:-..}

git config --global --add safe.directory $TARGET

cd $TARGET
if [ -f .pre-commit-config.yaml ]; then
    pre-commit run -a
else
    flake8 -v .
fi
rst-lint README.rst
