#!/bin/sh

source /infra/utils

set -e
set -u
set -x

printf "travis_fold:start:py-setup\n"


TARGET=${TARGET:-..}

cd $TARGET
cd $(setup_dir)
python setup.py sdist
pip install dist/*.tar.gz
python setup.py clean
rm -rf dist *egg-info src/*egg-info

printf "travis_fold:end:py-setup\n"
