#!/bin/bash

set -e
set -u
set -x

printf "travis_fold:start:scripts-build\n"

export TARGET=${TARGET:-..}
export OMERO_DIST=${OMERO_DIST:-/opt/omero/server/OMERO.server/}
export PYTHONPATH=${OMERO_DIST}/lib/python

rm -rf $OMERO_DIST/lib/scripts/omero

cd $TARGET
cp -r omero $OMERO_DIST/lib/scripts/
python setup.py test -t test/integration -i ${OMERO_DIST}/etc/ice.config -v

printf "travis_fold:end:scripts-build\n"
