#!/bin/bash

setup_dir() {
    # check the location of setup.py
    ref_file="setup.py"
    directory="./"
    values=()
    if [ ! -f $ref_file ]; then
        values=$(find "$(pwd -P)" -name $ref_file)
        if [ ${#values[@]} == 1 ]; then
            directory=$(dirname ${values[0]})
        fi
    fi
    echo $directory
}

get_app_name() {
    # convert the directory name into the app name
    echo $(echo $(basename $PWD) | tr - _)
}

get_project_name() {
   echo $(get_app_name | tr -cd '[[:alnum:]]')
}
