#!/bin/bash

OMERO_DIST=${OMERO_DIST:-/opt/omero/server/OMERO.server}
if [ ! -e $OMERO_DIST ];
then
    OMERO_DIST=/opt/omero/web/OMERO.web
fi

OMERO_HOST=${OMERO_HOST:-localhost}
OMERO_PORT=${OMERO_PORT:-4064}
OMERO_USER=${OMERO_USER:-root}
OMERO_PASS=${OMERO_PASS:-omero}

export PATH=$PATH:${OMERO_DIST}/bin


max_attempts=10
attempt_num=1

function end {
    printf "travis_fold:end:wait-on-login\n"
}

trap end EXIT

printf "travis_fold:start:wait-on-login\n"
until omero login $OMERO_USER@$OMERO_HOST:$OMERO_PORT -w $OMERO_PASS 2>&1 >/dev/null
do
    if (( attempt_num == max_attempts ))
    then
        echo "All attempts failed"
        exit 1
    fi

    echo "Attempt $(( attempt_num++ )) failed. Trying again in $attempt_num seconds..."
    sleep $attempt_num

done
